run_name: EEVE-completed-only-cot-expand-lora-target
model_id: yanolja/EEVE-Korean-Instruct-10.8B-v1.0
resume: False

lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "up_proj", "down_proj", "gate_proj"]
lora_r: 8
lora_alpha: 16

epochs: 5
batch_size: 1
gradient_accumulation_steps: 32
lr: 0.00001
